name: udemy-microservice

networks:
  nakoual:
    driver: bridge

services:
  accounts:
    image: "nakoual/accounts:udemy"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nakoual
  cards:
    image: "nakoual/cards:udemy"
    container_name: cards-ms
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nakoual
  loans:
    image: "nakoual/loans:udemy"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nakoual

